Repository Materials-Consortia/OPTIMADE, pull requests merged in 2019-06, with the labels that each got.

#47 Handle unset optional properties
  .DS_Store
  optimade.md
Labels: PR/ready-for-review

#108 update readme
  README.md
Labels: PR/minor-fixes-only, PR/ready-for-review

#110 update authors
  AUTHORS
Labels: PR/minor-fixes-only, PR/ready-for-review

#113 Removing .DS_Store and preventing it from being added again
  .DS_Store
  .gitignore
Labels: PR/ready-for-review

#85 Introducing 'warnings' list in 'meta'
  optimade.md
Labels: PR/ready-for-review

#115 Removing all references to the entrypoint `/all`
  .github/PULL_REQUEST_TEMPLATE.md
  AUTHORS
  optimade.md
Labels: PR/ready-for-review

#93 Adding support for unknown coordinates
  optimade.md
Labels: PR/ready-for-review

#121 Allowing comments in JSON snippets and clarifying floats
  optimade.md
Labels: PR/ready-for-review

#95 Introducing relationships for references and provenance
  optimade.md
Labels: PR/ready-for-review

#120 Making a pair of intended RFC2119 keywords uppercase
  optimade.md
Labels: PR/ready-for-review

#122 Small spelling and grammar fixes
  .words.lst
  optimade.md
Labels: PR/minor-fixes-only, PR/ready-for-review

#97 sorting and pagination updates
  .gitignore
  optimade.md
Labels: PR/ready-for-review

#126 (Re)define `property`
  optimade.md
Labels: PR/minor-fixes-only, PR/ready-for-review, priority/high

#100 Update/addition of various properties related to chemical formula
  optimade.md
Labels: PR/minor-fixes-only, PR/ready-for-review

#132 Add starting symbol limitation for field
  optimade.md
Labels: PR/minor-fixes-only, PR/ready-for-review, status/approved

#131 Fix in filter language examples: 'HAS, EXACTLY' -> 'HAS EXACTLY'.
  optimade.md
Labels: PR/ready-for-review, type/minor-fix

#127 Species redesign
  optimade.md
Labels: PR/ready-for-review

#79 [WIP] Update README in master-branch to guide client/server developers
  README.md
Labels: PR/ready-for-review

#135 Reworking the last occurrence of old-style `species`
  optimade.md
Labels: PR/ready-for-review

#136 Minor typos and tidying
  optimade.md
Labels: PR/ready-for-review

#128 structure -> structures, calculation -> calculations
  optimade.md
Labels: PR/minor-fixes-only

#140 Updated: allow web-browsers to issue cross-domain requests
  optimade.md
Labels: PR/ready-for-review

#142 Filtering using nested property names and on relationships
  optimade.md
Labels: PR/ready-for-review, blocking-release

#138 Set operators
  optimade.md
  tests/inputs/set.filter
  tests/inputs/set2.filter
  tests/inputs/set3.filter
  tests/inputs/set4.filter
  tests/inputs/setzip-spaces.filter
  tests/inputs/setzip.filter
  tests/outputs/Filter_032.out
  tests/outputs/Filter_033.out
  tests/outputs/Filter_035.out
  tests/outputs/Filter_037.out
  tests/outputs/Filter_039.out
  tests/outputs/Filter_054.out
  tests/outputs/Filter_055.out
  tests/outputs/Filter_068.out
Labels: PR/minor-fixes-only, PR/ready-for-review, blocking-release

#143 Additions to providers.json
  providers.json
Labels: PR/ready-for-review

#145 Introducing timestamp data type
  optimade.md
Labels: PR/minor-fixes-only, PR/ready-for-review

#148 fix example json (remove spurious commas)
  optimade.md
Labels: PR/minor-fixes-only, PR/ready-for-review
