Repository Materials-Consortia/OPTIMADE, pull requests merged in 2019-07, with the labels that each got.

#137 clarify JSON API connection
  optimade.md
Labels: PR/minor-fixes-only, PR/ready-for-review

#150 Clarify querability, greater separation between types and representations
  optimade.md
Labels: PR/ready-for-review, blocking-release

#154 Fix available_api_versions so the same version can be at more than one URL
  optimade.md
Labels: PR/ready-for-review, blocking-release

#144 Fixes in type conversion rules
  optimade.md
Labels: PR/requires-discussion, blocking-release

#156 Fix UnicodeHighChar comment
  optimade.md
Labels: PR/ready-for-review

#158 Restructuring the entry listing info endpoint
  optimade.md
Labels: PR/ready-for-review

#165 Dropping restrictions on the IDs
  optimade.md
Labels: PR/ready-for-review

#168 Fixing description that looks like a grammar (or logic) mistake.
  optimade.md
Labels: PR/ready-for-review

#159 Define returning properties with unknown values
  optimade.md
Labels: PR/ready-for-review
