Repository Materials-Consortia/OPTIMADE, pull requests merged in 2019-12, with the labels that each got.

#214 Update mcloud provider index base URL
  providers.json
Labels: PR/ready-for-review

#220 Clarify `data_returned`, `data_available`, and `more_data_available`
  optimade.rst
Labels: PR/ready-for-review

#216 Fix the definition of cartesian_site_positions length
  optimade.rst
Labels: PR/ready-for-review, type/bug

#219 Add `include` query parameter and be more explicit about top-level `included`
  optimade.rst
Labels: PR/ready-for-review

#222 Change to externally maintained providers.json
  optimade.rst
  providers.json
Labels: PR/ready-for-review

#162 Adding description of unknown property name handling
  .words.lst
  optimade.rst
Labels: PR/ready-for-review

#223 Standard capitalization for abbreviations
  optimade.rst
Labels: PR/ready-for-review, type/minor-fix

#221 Refining the grammar of the `LengthComparison`
  optimade.rst
  tests/cases/Filter_028.inp
  tests/inputs/length.filter
  tests/inputs/length2.filter
  tests/inputs/length2_fail.filter
  tests/inputs/length3.filter
  tests/inputs/length4_fail.filter
  tests/inputs/length_fail.filter
  tests/outputs/Filter_015.out
  tests/outputs/Filter_019.out
  tests/outputs/Filter_020.out
  tests/outputs/Filter_021.out
  tests/outputs/Filter_022.out
  tests/outputs/Filter_023.out
  tests/outputs/Filter_024.out
  tests/outputs/Filter_026.out
  tests/outputs/Filter_027.out
  tests/outputs/Filter_028.out
  tests/outputs/Filter_029.out
  tests/outputs/Filter_030.out
  tests/outputs/Filter_031.out
  tests/outputs/Filter_059.out
  tests/outputs/Filter_060.out
  tests/outputs/Filter_064.out
  tests/outputs/Filter_065.out
  tests/outputs/Filter_070.out
  tests/outputs/Filter_072.out
Labels: PR/ready-for-review

#189 Minor rst updates - no content changes
  optimade.rst
Labels: PR/ready-for-review, type/minor-fix

#195 Makefile reorganization, validation in docker
  .travis.yml
  GNUmakefile
  tests/makefiles/Makelocal-audit
  tests/makefiles/Makelocal-authors
  tests/makefiles/Makelocal-docker
  tests/makefiles/Makelocal-grammars
  tests/makefiles/Makelocal-output
  tests/makefiles/Makelocal-spell
  tests/makefiles/Makelocal-tools
  tests/tools/Dockerfile
Labels: PR/ready-for-review

#213 Add CC-BY 4.0 license for the specification
  LICENSE
Labels: PR/ready-for-review, blocking-release

#226 Fix broken link in README
  README.md
Labels: PR/minor-fixes-only, PR/ready-for-review

#210 Common rules for inclusion and querying
  optimade.rst
Labels: PR/ready-for-review

#228 Add 'homepage_url' to providers.json
  optimade.rst
Labels: PR/ready-for-review

#234 Remove missed obsolete statement about providers.json
  optimade.rst
Labels: PR/ready-for-review, type/bug

#232 Correct the description of where relationships should go
  optimade.rst
Labels: PR/ready-for-review, type/bug

#227 Explain what to return for requests to the base url
  optimade.rst
Labels: PR/ready-for-review

#229 Forbid constant <op> constant comparisons for strings
  optimade.rst
Labels: PR/ready-for-review

#231 Clarify use of null in lattice_vectors
  optimade.rst
Labels: PR/ready-for-review

#233 Standardize all use of RFC2119-type terms
  optimade.rst
Labels: PR/ready-for-review

#230 Fix string value example
  optimade.rst
Labels: PR/ready-for-review
