Repository Materials-Consortia/OPTIMADE, pull requests merged in 2020-11, with the labels that each got.

#333 Migrate CI from Travis to GitHub Actions
  .github/workflows/ci.yml
  .github/workflows/precommit.yml
Labels: priority/low, topic/infrastructure

#335 Validate OpenAPI schemas in CI with validator.swagger.io
  .github/workflows/ci.yml
  .travis.yml
  tests/makefiles/Makelocal-audit
  tests/makefiles/Makelocal-swagger
  tests/scripts/validate_swagger.sh
Labels: PR/ready-for-review, topic/infrastructure, topic/validation

#339 Add field for implementation issue tracker
  optimade.rst
Labels: PR/ready-for-review

#338 Fix incorrect example in assemblies
  optimade.rst
Labels: PR/ready-for-review
