Repository Materials-Consortia/OPTIMADE, pull requests merged in 2020-07, with the labels that each got.

#299 Define units per The Unified Code for Units of Measure
  optimade.rst
Labels: PR/ready-for-review

#302 Fix text referencing API being served (only) under versioned URLs
  optimade.rst
Labels: PR/minor-fixes-only, PR/ready-for-review

#300 Minor text fixes in preparation for v1.0.0 release
  optimade.rst
Labels: PR/minor-fixes-only

#298 Fixes to meta tag description, add link to schema
  optimade.rst
Labels: PR/ready-for-review

#303 Update schemas for v1.0.0
  schemas/index_openapi_schema.json
  schemas/openapi_schema.json
Labels: blocking-release, priority/high

#313 Fixing a typo: 'severing' -> 'serving'
  optimade.rst
Labels: PR/minor-fixes-only, PR/ready-for-review, type/minor-fix
