Repository Materials-Consortia/OPTIMADE, pull requests merged in 2020-06, with the labels that each got.

#236 Relaxed requirements for index meta-databases to support static hosting
  optimade.rst
Labels: PR/ready-for-review

#273 Extend (and change) the definition of links endpoints
  optimade.rst
Labels: PR/ready-for-review

#284 Adding the aggregate option for links
  optimade.rst
Labels: PR/ready-for-review, event/workshop-2020

#278 Added nperiodic_dimensions field
  optimade.rst
Labels: PR/ready-for-review, priority/high

#282 Add `type` key to properties (simple)
  optimade.rst
Labels: PR/ready-for-review, priority/high, status/approved

#264 Custom endpoints should be under `/extensions`
  optimade.rst
Labels: PR/minor-fixes-only, PR/ready-for-review

#279 New representation of atoms at unknown positions
  optimade.rst
Labels: PR/ready-for-review, priority/high

#287 Fixing tiny typo in the date/time examples
  optimade.rst
Labels: PR/ready-for-review, type/minor-fix

#288 Adjust query requirements on dimension_types
  optimade.rst
Labels: PR/ready-for-review, blocking-release, priority/high

#289 Formatting fixes
  optimade.rst
Labels: PR/minor-fixes-only, PR/ready-for-review, blocking-release

#291 Updated OpenAPI spec to ready for 1.0.0-rc.2
  schemas/index_openapi_schema.json
  schemas/openapi_schema.json
Labels: PR/ready-for-review, blocking-release

#290 Serving the API on the unversioned base URL
  optimade.rst
Labels: PR/ready-for-review, blocking-release, priority/high
