Repository Materials-Consortia/OPTIMADE, pull requests merged in 2021-07, with the labels that each got.

#372 Adapt creation of AUTHORS.sorted to changes in format of AUTHORS
  tests/makefiles/Makelocal-authors
Labels: blocking-release

#373 Minor typo fix
  optimade.rst
Labels: PR/minor-fixes-only

#370 Add v1.1.0 schemas from optimade-python-tools v0.16.0
  schemas/index_openapi_schema.json
  schemas/openapi_schema.json
Labels: PR/ready-for-review, blocking-release, priority/high

#380 Add v1.0.1 to CHANGELOG
  CHANGELOG.md
Labels: PR/minor-fixes-only
