Repository Materials-Consortia/OPTIMADE, pull requests merged in 2022-06, with the labels that each got.

#405 Space group additions: `space_group_hall` and `space_group_it_number`
  optimade.rst
Labels: topic/property-standardization, type/proposal, status/has-concrete-suggestion

#394 Clarify description dimension_types + small corrections
  optimade.rst
Labels: PR/minor-fixes-only

#360 Files endpoint
  optimade.rst
Labels: PR/ready-for-review

#376 Property definitions
  optimade.rst
Labels: PR/ready-for-review

#415 Support fuzzy comparison lists
  optimade.rst
  tests/cases/Filter_080.inp
  tests/cases/Filter_080.opt
  tests/cases/Filter_081.inp
  tests/cases/Filter_081.opt
  tests/cases/Filter_082.inp
  tests/cases/Filter_082.opt
  tests/outputs/Filter_032.out
  tests/outputs/Filter_037.out
  tests/outputs/Filter_080.out
  tests/outputs/Filter_081.out
  tests/outputs/Filter_082.out
Labels: topic/filtering-language, type/proposal, PR/ready-for-review

#411 Backoff time
  optimade.rst
Labels: type/proposal

#414 Means to specify database license
  optimade.rst
Labels: topic/property-standardization, type/proposal, PR/ready-for-review
