Repository Materials-Consortia/OPTIMADE, pull requests merged in 2022-12, with the labels that each got.

#432 Update Swagger CI test to use latest online validator format
  tests/scripts/validate_swagger.sh
Labels: type/minor-fix, PR/ready-for-review, topic/infrastructure

#444 Clarify encoding of OPTIMADE timestamp in property definitions.
  optimade.rst
Labels: blocking-release

#430 OPTIMADE v1.2.0-rc.1 release prep
  .pre-commit-config.yaml
  .words.lst
  AUTHORS
  CHANGELOG.md
  README.md
  optimade.rst
Labels: priority/high, blocking-release
