Repository Materials-Consortia/OPTIMADE, pull requests merged in 2023-06, with the labels that each got.

#467 Partial data
  .words.lst
  optimade.rst
Labels: PR/ready-for-review

#463 Add per entry and per property meta data field.
  optimade.rst
Labels: PR/ready-for-review

#424 Add `database` field to `meta` for describing the current database
  optimade.rst
Labels: PR/ready-for-review

#472 Add `type` and `id` to the entry info endpoints
  optimade.rst
Labels: type/bug, status/has-concrete-suggestion, topic/info-endpoint, PR/ready-for-review

#475 Tiny whitespace fix for broken formatting
  optimade.rst
Labels: PR/minor-fixes-only, PR/ready-for-review
