Repository Materials-Consortia/OPTIMADE, pull requests merged in 2024-03, with the labels that each got.

#378 Adding an HTML build of the specification
  .github/workflows/pages.yml
  tests/makefiles/Makelocal-output
  tests/makefiles/style.css
Labels: type/proposal, topic/infrastructure

#473 Definition namespaces and providers
  .words.lst
  optimade.rst
Labels: PR/ready-for-review, blocking-release

#490 Define OPTIMADE regex format
  optimade.rst
Labels: topic/filtering-language, topic/property-standardization, PR/ready-for-review, blocking-release

#503 Updates to HTML build in CI
  .github/workflows/pages.yml
  .gitignore
  tests/makefiles/style.css
Labels: blocking-release

#488 Add ECMA definition of symmetry operation regexp and associated tests
  GNUmakefile
  optimade.rst
  tests/cases/ecma_symops_001.sh
  tests/cases/symops_pcre_to_ecma_001.sh
  tests/makefiles/Makelocal-grammars
  tests/outputs/ecma_symops_001.out
  tests/outputs/symops_pcre_to_ecma_001.out
Labels: blocking-release, status/blocked
