Repository Materials-Consortia/OPTIMADE, pull requests merged in 2025-09, with the labels that each got.

#557 Add property definitions for `fractional_site_positions`
  schemas/src/defs/v1.3/entrytypes/optimade/structures.yaml
  schemas/src/defs/v1.3/properties/optimade/structures/fractional_site_positions.yaml
  schemas/src/defs/v1.3/standards/optimade.yaml
Labels: blocking-release, topic/property-definitions

#377 Adding the trajectories endpoint to OPTIMADE
  optimade.rst
Labels: type/proposal, PR/major-edits

#566 Introduce Contributor Covenant code of conduct
  CODE_OF_CONDUCT.md
Labels: PR/requires-discussion, blocking-release
